kind: Service
apiVersion: v1
metadata:
  name: web-clustering-ping
  namespace: myproject
  labels:
    application: web-clustering
  annotations:
    description: The JGroups ping port for clustering.
    service.alpha.kubernetes.io/tolerate-unready-endpoints: 'true'
spec:
  ports:
    - name: ping
      protocol: TCP
      port: 8888
      targetPort: 8888
  selector:
    deployment: web-clustering
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
  publishNotReadyAddresses: true
status:
  loadBalancer: {}

