wildfly-bootable:
    socket-binding-group:
        standard-sockets:
          default-interface: public
          port-offset: ${jboss.socket.binding.port-offset:99}
          socket-binding:
              http:
                interface: public
              https:
          remote-destination-outbound-socket-binding:
            mail-snmt:  
              host: foo
              port: 8081
            foo2:
              host: foo2
              port: 8082
    system-property:
      aaa: 
        value: foo
      bbb:
        value: bar
    subsystem:
        microprofile-config-smallrye:
          config-source:
            foo:
              dir: 
                path: /home/jdenise
              ordinal: 200
        microprofile-opentracing-smallrye:
          default-tracer: toto
          jaeger-tracer:
            toto:
              sampler-param: 30.0
        weld:
          require-bean-descriptor: true
        logging:
          logger:
            com.foo:
              level: ALL
            com.demo:
              level: WARN
          root-logger:
            ROOT:
              handlers: "[\"CONSOLE\"]"
              level: INFO
        metrics:
        ee:
          annotation-property-replacement: true
          spec-descriptor-property-replacement: true
        jca:
          workmanager:
            foo:
                name: foo
                short-running-threads:
                  foo-short:
                    core-threads: 50
                    max-threads: 50
                    queue-length: 50
                    keepalive-time:
                      time: 10
                      unit: SECONDS
        elytron:
          filesystem-realm:
            exampleFsRealm:
              path: fs-realm-users
              relative-to: jboss.server.config.dir
          security-domain:
             exampleSD:
               realms:
               - realm: exampleFsRealm 
               permission-mapper: default-permission-mapper
               default-realm: exampleFsRealm
          http-authentication-factory:
             example-http-auth:
               http-server-mechanism-factory: global
               security-domain: exampleSD
               mechanism-configurations:
               - mechanism-name: DIGEST
                 mechanism-realm-configurations:
                 - realm-name: exampleFsRealm 
             example-http-auth2:
               http-server-mechanism-factory: global
               security-domain: exampleSD
               mechanism-configurations:
               - mechanism-name: DIGEST
                 mechanism-realm-configurations:
                 - realm-name: exampleFsRealm 
          properties-realm:
            MyApplicationRealm:
              groups-properties:
                path: application-roles.properties
                relative-to: jboss.server.config.dir
              users-properties:
                path: application-users.properties
                relative-to: jboss.server.config.dir
          permission-set:
           default-permissions: 
             permissions:
             - class-name: org.wildfly.transaction.client.RemoteTransactionPermission
               module: org.wildfly.transaction.client
               target-name: "*"
             - class-name: org.wildfly.transaction.client.RemoteTransactionPermission
               module: org.wildfly.transaction.client
               target-name: "*"
           my-permissions:
             permissions:
             - class-name: org.wildfly.transaction.client.RemoteTransactionPermission
               module: org.wildfly.transaction.client
               target-name: "*"
             - class-name: org.wildfly.transaction.client.RemoteTransactionPermission
               module: org.wildfly.transaction.client
               target-name: "*"
    core-service:
      management:
        management-interface:
          http-interface:
              console-enabled: true
              http-upgrade:
                enabled: true
              constant-headers:
              - path: /foo
                headers:
                - name: foo
                  value: bar
              - path: /foo2
                headers:
                - name: foo2
                  value: bar 
        access:
          authorization:
            provider: simple
            use-identity-roles: true
            constraint:
              application-classification:
                type:
                  logging:
                    classification:
                      logger:
                        configured-application: true
            
